import Head from 'next/head';
import Header from './components/Header';
import Footer from "./components/Footer";
import styles from '../styles/Home.module.css';
import {useEffect} from "react";
import Link from 'next/link';
import {FaSearch} from 'react-icons/fa';


function Home() {
    const callAPI = async () => {
        try {
            const url = process.env.NEXT_PUBLIC_BACKEND_HOST + `/posts/1`;
            const res = await fetch(url);
            const data = await res.json();
            console.log(data);
        } catch (err) {
            console.log(err);
        }
    };

    return (
        <main className="d-flex flex-column min-vh-100">

            <Head>
                <title>App NextJS</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header/>

            <nav className="navbar navbar-expand-lg navbar-light bg-light"
                 style={{backgroundColor: 'lightblue !important'}}>
                <div className="container px-4 px-lg-5">
                    <div className="row" style={{
                        width: "100%"
                    }}>
                        <div className="col-2">
                            <select className="form-select form-select-lg" aria-label=".form-select-lg example"
                                    style={{
                                        fontSize: '0.8rem',
                                    }}>
                                <option selected>Tất cả</option>
                                <option value="1">Hà Nội</option>
                                <option value="2">Tp. Hồ Chí Minh</option>
                                <option value="3">Đà Nẵng</option>
                            </select>
                        </div>
                        <div className="col-2">
                            <select className="form-select form-select-lg" aria-label=".form-select-lg example"
                                    style={{
                                        fontSize: '0.8rem',
                                    }}>
                                <option selected>Tất cả</option>
                                <option value="1">Ăn uống</option>
                                <option value="2">Khách sạn</option>
                                <option value="3">Thời trang</option>
                            </select>
                        </div>
                        <div className="col-4">
                            <div className="input-group">
                                <input className="form-control border-end-0 border" type="text"
                                       placeholder="search"
                                       id="example-search-input"
                                       style={{
                                           fontSize: '0.8rem'
                                       }}></input>
                                <span className="input-group-append">
                                    <button
                                        className="btn btn-outline-secondary bg-white border-start-0 border ms-n3"
                                        type="button">
                                        <FaSearch/>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>

            <div className="bg-dark py-5" style={{
                backgroundImage: "url('/image/banner_image.jpg')",
                backgroundRepeat: "no-repeat",
                backgroundSize: "cover",
            }}>
                <div className="container px-4 px-lg-5 my-5">
                    <div className="text-center text-white">
                        <h1 className="display-4 fw-bolder">Shop in style</h1>
                        <p className="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
                    </div>
                </div>
            </div>

            <section className="py-5">
                <div className="container px-4 px-lg-5 mt-5 card">
                    <div className="card-body">
                        <div className="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                            <div className="col mb-5">
                                <div className="card h-100">
                                    <img className="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg"
                                         alt="..."/>
                                    <div className="card-body p-4">
                                        <div className="text-center">
                                            <h5 className="fw-bolder">Fancy Product</h5>
                                            $40.00 - $80.00
                                        </div>
                                    </div>
                                    <div className="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div className="text-center"><a className="btn btn-outline-dark mt-auto"
                                                                        href="#">View
                                            options</a></div>
                                    </div>
                                </div>
                            </div>
                            <div className="col mb-5">
                                <div className="card h-100">
                                    <div className="badge bg-dark text-white position-absolute"
                                         data-style="top: 0.5rem; right: 0.5rem">Sale
                                    </div>
                                    <img className="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg"
                                         alt="..."/>
                                    <div className="card-body p-4">
                                        <div className="text-center">
                                            <h5 className="fw-bolder">Special Item</h5>
                                            <div className="d-flex justify-content-center small text-warning mb-2">
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                            </div>
                                            <span className="text-muted text-decoration-line-through">$20.00</span>
                                            $18.00
                                        </div>
                                    </div>
                                    <div className="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div className="text-center"><a className="btn btn-outline-dark mt-auto"
                                                                        href="#">Add
                                            to cart</a></div>
                                    </div>
                                </div>
                            </div>
                            <div className="col mb-5">
                                <div className="card h-100">
                                    <div className="badge bg-dark text-white position-absolute"
                                         data-style="top: 0.5rem; right: 0.5rem">Sale
                                    </div>
                                    <img className="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg"
                                         alt="..."/>
                                    <div className="card-body p-4">
                                        <div className="text-center">
                                            <h5 className="fw-bolder">Sale Item</h5>
                                            <span className="text-muted text-decoration-line-through">$50.00</span>
                                            $25.00
                                        </div>
                                    </div>
                                    <div className="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div className="text-center"><a className="btn btn-outline-dark mt-auto"
                                                                        href="#">Add
                                            to cart</a></div>
                                    </div>
                                </div>
                            </div>
                            <div className="col mb-5">
                                <div className="card h-100">
                                    <img className="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg"
                                         alt="..."/>
                                    <div className="card-body p-4">
                                        <div className="text-center">
                                            <h5 className="fw-bolder">Popular Item</h5>
                                            <div className="d-flex justify-content-center small text-warning mb-2">
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                            </div>
                                            $40.00
                                        </div>
                                    </div>
                                    <div className="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div className="text-center"><a className="btn btn-outline-dark mt-auto"
                                                                        href="#">Add
                                            to cart</a></div>
                                    </div>
                                </div>
                            </div>
                            <div className="col mb-5">
                                <div className="card h-100">
                                    <div className="badge bg-dark text-white position-absolute"
                                         data-style="top: 0.5rem; right: 0.5rem">Sale
                                    </div>
                                    <img className="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg"
                                         alt="..."/>
                                    <div className="card-body p-4">
                                        <div className="text-center">
                                            <h5 className="fw-bolder">Sale Item</h5>
                                            <span className="text-muted text-decoration-line-through">$50.00</span>
                                            $25.00
                                        </div>
                                    </div>
                                    <div className="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div className="text-center"><a className="btn btn-outline-dark mt-auto"
                                                                        href="#">Add
                                            to cart</a></div>
                                    </div>
                                </div>
                            </div>
                            <div className="col mb-5">
                                <div className="card h-100">
                                    <img className="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg"
                                         alt="..."/>
                                    <div className="card-body p-4">
                                        <div className="text-center">
                                            <h5 className="fw-bolder">Fancy Product</h5>
                                            $120.00 - $280.00
                                        </div>
                                    </div>
                                    <div className="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div className="text-center"><a className="btn btn-outline-dark mt-auto"
                                                                        href="#">View
                                            options</a></div>
                                    </div>
                                </div>
                            </div>
                            <div className="col mb-5">
                                <div className="card h-100">
                                    <div className="badge bg-dark text-white position-absolute"
                                         data-style="top: 0.5rem; right: 0.5rem">Sale
                                    </div>
                                    <img className="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg"
                                         alt="..."/>
                                    <div className="card-body p-4">
                                        <div className="text-center">
                                            <h5 className="fw-bolder">Special Item</h5>
                                            <div className="d-flex justify-content-center small text-warning mb-2">
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                            </div>
                                            <span className="text-muted text-decoration-line-through">$20.00</span>
                                            $18.00
                                        </div>
                                    </div>
                                    <div className="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div className="text-center"><a className="btn btn-outline-dark mt-auto"
                                                                        href="#">Add
                                            to cart</a></div>
                                    </div>
                                </div>
                            </div>
                            <div className="col mb-5">
                                <div className="card h-100">
                                    <img className="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg"
                                         alt="..."/>
                                    <div className="card-body p-4">
                                        <div className="text-center">
                                            <h5 className="fw-bolder">Popular Item</h5>
                                            <div className="d-flex justify-content-center small text-warning mb-2">
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                                <div className="bi-star-fill"></div>
                                            </div>
                                            $40.00
                                        </div>
                                    </div>
                                    <div className="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div className="text-center"><a className="btn btn-outline-dark mt-auto"
                                                                        href="#">Add
                                            to cart</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <Footer/>

            {/* eslint-disable-next-line @next/next/no-sync-scripts */}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        </main>
    )
}

export default Home;
